exclude: '^docs/build/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.svg$'
      - id: end-of-file-fixer
        exclude: '\.svg$'
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: julia-formatter
        name: Julia Formatter
        entry: pixi r julia --project=. -e 'using JuliaFormatter; format(ARGS)'
        language: system
        types: [julia]
        pass_filenames: true
