name = "ChemGP"
uuid = "eed806ec-7d39-480c-b706-b5b92225bb88"
authors = ["Rohit Goswami"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
