[deps]
ChemGP = "eed806ec-7d39-480c-b706-b5b92225bb88"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[sources]
ChemGP = {path = "/home/rgoswami/Git/Github/Julia/ChemGP"}

[compat]
Documenter = "1"
